export { Application, type ApplicationOptions } from './core/application';
export { BunServer, type ServerOptions } from './core/server';
export { Context } from './core/context';
export { ContextService, CONTEXT_SERVICE_TOKEN, contextStore } from './core/context-service';
export { Route, Router, RouteRegistry } from './router';
export { GET, POST, PUT, DELETE, PATCH } from './router/decorators';
export type { HttpMethod, RouteHandler, RouteMatch } from './router/types';
export { BodyParser, RequestWrapper, ResponseBuilder } from './request';
export {
  Body,
  Query,
  QueryMap,
  Param,
  Header,
  HeaderMap,
  ParamBinder,
  Controller,
  ControllerRegistry,
} from './controller';
export { Context as ContextParam } from './controller';
export type {
  ParamMetadata,
  QueryMapOptions,
  HeaderMapOptions,
  ControllerMetadata,
} from './controller';
export { Container } from './di/container';
export { Injectable, Inject } from './di/decorators';
export { Lifecycle, type ProviderConfig, type DependencyMetadata } from './di/types';
export {
  Module,
  type ModuleMetadata,
  type ModuleProvider,
  type ModuleClass,
} from './di/module';
export { ModuleRegistry } from './di/module-registry';
export {
  InterceptorRegistry,
  InterceptorChain,
  scanInterceptorMetadata,
  BaseInterceptor,
  Cache,
  CacheInterceptor,
  Permission,
  PermissionInterceptor,
  Log,
  LogInterceptor,
  INTERCEPTOR_REGISTRY_TOKEN,
  CACHE_METADATA_KEY,
  PERMISSION_METADATA_KEY,
  LOG_METADATA_KEY,
  type Interceptor,
  type InterceptorMetadata,
  type CacheOptions,
  type PermissionOptions,
  type PermissionService,
  type LogOptions,
} from './interceptor';
export { UseMiddleware, RateLimit, MiddlewarePipeline } from './middleware';
export type { Middleware, NextFunction } from './middleware';
export {
  createLoggerMiddleware,
  createRequestLoggingMiddleware,
  createErrorHandlingMiddleware,
  createCorsMiddleware,
  createFileUploadMiddleware,
  createStaticFileMiddleware,
  createRateLimitMiddleware,
  createTokenKeyGenerator,
  createUserKeyGenerator,
  type RateLimitOptions,
  type RateLimitStore,
} from './middleware/builtin';
// Validation 模块
export {
  // 基础装饰器
  Validate,
  IsString,
  IsNumber,
  IsEmail,
  IsOptional,
  MinLength,
  getValidationMetadata,
  // 类型
  type ValidationRuleDefinition,
  type ValidationMetadata,
  type ClassValidationMetadata,
  type ValidationOptions,
  // 验证器
  validateParameters,
  // 错误处理
  ValidationError,
  type ValidationIssue,
  // 对象规则
  IsObject,
  IsNotEmpty,
  IsNotEmptyObject,
  ValidateNested,
  type ObjectRuleOptions,
  type ValidateNestedOptions,
  // 数组规则
  IsArray,
  ArrayMinSize,
  ArrayMaxSize,
  ArrayUnique,
  ArrayContains,
  ArrayNotContains,
  ArrayNotEmpty,
  type ArrayRuleOptions,
  // 通用规则
  IsBoolean,
  IsInt,
  IsPositive,
  IsNegative,
  Min,
  Max,
  IsDate,
  IsUUID,
  Length,
  MaxLength,
  Matches,
  IsIn,
  IsNotIn,
  IsUrl,
  IsJSON,
  Equals,
  NotEquals,
  IsDefined,
  IsAlphanumeric,
  IsAlpha,
  IsNumberString,
  type RuleOptions,
  type UUIDVersion,
  // 条件和转换规则
  ValidateIf,
  Transform,
  type ConditionalRuleOptions,
  // 自定义验证器
  createCustomValidator,
  createSimpleValidator,
  createRegexValidator,
  IsPhoneNumber,
  IsIdCard,
  IsIPv4,
  IsPort,
  IsPostalCode,
  IsCreditCard,
  IsHexColor,
  IsMacAddress,
  IsSemVer,
  IsDivisibleBy,
  IsBetween,
  Contains,
  NotContains,
  type CustomValidatorOptions,
  // 类级别验证
  ValidateClass,
  Property,
  NestedProperty,
  ArrayNestedProperty,
  validateObject,
  validateObjectSync,
  getClassValidationMetadata,
  isValidateClass,
} from './validation';
export {
  HttpException,
  BadRequestException,
  UnauthorizedException,
  ForbiddenException,
  NotFoundException,
  InternalServerErrorException,
  ExceptionFilterRegistry,
  type ExceptionFilter,
} from './error';
export {
  WebSocketGateway,
  OnOpen,
  OnMessage,
  OnClose,
  WebSocketGatewayRegistry,
  type WebSocketConnectionData,
} from './websocket';
export {
  LoggerExtension,
  LoggerModule,
  LogLevel,
  LOGGER_TOKEN,
  type Logger,
  type LoggerOptions,
  type LoggerModuleOptions,
  type LogEntry,
} from './extensions';
export {
  SwaggerExtension,
  SwaggerModule,
  SwaggerGenerator,
  createSwaggerUIMiddleware,
  ApiTags,
  ApiOperation,
  ApiParam,
  ApiBody,
  ApiResponse,
  type SwaggerOptions,
  type SwaggerModuleOptions,
  type SwaggerDocument,
  type ApiOperationMetadata,
  type ApiParamMetadata,
  type ApiBodyMetadata,
  type ApiResponseMetadata,
} from './swagger';
// Security 模块（推荐使用）
export {
  SecurityModule,
  SecurityContextHolder,
  AuthenticationManager,
  RoleBasedAccessDecisionManager,
  JwtAuthenticationProvider,
  OAuth2AuthenticationProvider,
  createSecurityFilter,
  getGuardRegistry,
  registerReflector,
  type SecurityModuleConfig,
  type SecurityConfig,
  type SecurityContext,
  type Authentication,
  type AuthenticationProvider,
  type AuthenticationRequest,
  type Principal,
  type Credentials,
  type AccessDecisionManager,
} from './security';
// Guards 子模块
export {
  UseGuards,
  Roles,
  getGuardsMetadata,
  getRolesMetadata,
  AuthGuard,
  OptionalAuthGuard,
  RolesGuard,
  createRolesGuard,
  GuardRegistry,
  ExecutionContextImpl,
  Reflector,
  GUARDS_METADATA_KEY,
  GUARD_REGISTRY_TOKEN,
  ROLES_METADATA_KEY,
  REFLECTOR_TOKEN,
  type CanActivate,
  type ExecutionContext,
  type HttpArgumentsHost,
  type WsArgumentsHost,
  type GuardType,
  type GuardMetadata,
  type GuardOptions,
  type RolesGuardOptions,
} from './security/guards';
export {
  ConfigModule,
  ConfigService,
  CONFIG_SERVICE_TOKEN,
  type ConfigModuleOptions,
} from './config';
export {
  HealthModule,
  type HealthIndicator,
  type HealthIndicatorResult,
  type HealthStatus,
  type HealthModuleOptions,
  HEALTH_INDICATORS_TOKEN,
  HEALTH_OPTIONS_TOKEN,
} from './health';
export {
  MetricsModule,
  MetricsCollector,
  PrometheusFormatter,
  createHttpMetricsMiddleware,
  METRICS_SERVICE_TOKEN,
  METRICS_OPTIONS_TOKEN,
  type MetricsModuleOptions,
  type MetricType,
  type MetricLabels,
  type MetricValue,
  type MetricDataPoint,
  type CustomMetric,
} from './metrics';
export {
  DatabaseModule,
  DatabaseService,
  DatabaseConnectionManager,
  ConnectionPool,
  DatabaseHealthIndicator,
  DatabaseExtension,
  DATABASE_SERVICE_TOKEN,
  DATABASE_OPTIONS_TOKEN,
  type DatabaseModuleOptions,
  type DatabaseConfig,
  type DatabaseType,
  type ConnectionInfo,
  type ConnectionPoolOptions,
  type SqliteConfig,
  type PostgresConfig,
  type MysqlConfig,
  // ORM exports
  Entity,
  Column,
  PrimaryKey,
  Repository,
  BaseRepository,
  DrizzleBaseRepository,
  OrmService,
  ORM_SERVICE_TOKEN,
  getEntityMetadata,
  getColumnMetadata,
  getRepositoryMetadata,
  type OrmModuleOptions,
  type BaseRepository as BaseRepositoryInterface,
  type EntityMetadata,
  type ColumnMetadata,
  // Transaction exports
  Transactional,
  TransactionManager,
  TransactionInterceptor,
  Propagation,
  IsolationLevel,
  TransactionStatus,
  TRANSACTION_SERVICE_TOKEN,
  getTransactionMetadata,
  type TransactionOptions,
  type TransactionContext,
} from './database';
// Auth 模块（底层实现，供 Security 模块使用）
export {
  JWTUtil,
  OAuth2Service,
  OAuth2Controller,
  Auth,
  getAuthMetadata,
  requiresAuth,
  checkRoles,
  OAUTH2_SERVICE_TOKEN,
  JWT_UTIL_TOKEN,
  type JWTConfig,
  type JWTPayload,
  type OAuth2Client,
  type OAuth2AuthorizationRequest,
  type OAuth2TokenRequest,
  type OAuth2TokenResponse,
  type UserInfo,
  type AuthContext,
  type AuthConfig,
} from './auth';
export {
  PerformanceHarness,
  StressTester,
  type BenchmarkResult,
  type StressResult,
} from './testing/harness';
// Cache 模块
export {
  CacheModule,
  CacheService,
  Cacheable,
  CacheEvict,
  CachePut,
  EnableCacheProxy,
  CacheServiceProxy,
  CachePostProcessor,
  CacheableInterceptor,
  CacheEvictInterceptor,
  CachePutInterceptor,
  MemoryCacheStore,
  RedisCacheStore,
  CACHE_SERVICE_TOKEN,
  CACHE_OPTIONS_TOKEN,
  CACHE_POST_PROCESSOR_TOKEN,
} from './cache';
export type {
  CacheModuleOptions,
  CacheStore,
  RedisCacheStoreOptions,
  CacheableOptions,
  CacheEvictOptions,
  CachePutOptions,
} from './cache';
// Queue 模块
export {
  QueueModule,
  QueueService,
  Queue,
  Cron,
  MemoryQueueStore,
  QUEUE_SERVICE_TOKEN,
  QUEUE_OPTIONS_TOKEN,
} from './queue';
export type {
  QueueModuleOptions,
  QueueStore,
  Job,
  JobData,
  JobHandler,
  JobOptions,
  CronOptions,
  QueueOptions,
  CronDecoratorOptions,
} from './queue';
// Session 模块
export {
  SessionModule,
  SessionService,
  createSessionMiddleware,
  SessionDecorator as Session,
  MemorySessionStore,
  RedisSessionStore,
  SESSION_SERVICE_TOKEN,
  SESSION_OPTIONS_TOKEN,
} from './session';
export type {
  SessionModuleOptions,
  SessionStore,
  Session as SessionType,
  SessionData,
  RedisSessionStoreOptions,
} from './session';
// Microservice 模块
export {
  ConfigCenterModule,
  NacosConfigCenter,
  CONFIG_CENTER_TOKEN,
  type ConfigCenterModuleOptions,
  type ConfigCenterProvider,
  type NacosConfigCenterOptions,
  type ConfigCenter,
  type ConfigChangeListener,
  type ConfigResult,
} from './microservice';
export {
  ServiceRegistryModule,
  NacosServiceRegistry,
  SERVICE_REGISTRY_TOKEN,
  type ServiceRegistryModuleOptions,
  type ServiceRegistryProvider,
  type NacosServiceRegistryOptions,
  type ServiceRegistry,
  type GetInstancesOptions,
  type InstancesChangeListener,
  type ServiceInstance,
} from './microservice';
// Service Client 模块
export {
  ServiceClient,
  LoadBalancerFactory,
  RandomLoadBalancer,
  RoundRobinLoadBalancer,
  WeightedRoundRobinLoadBalancer,
  ConsistentHashLoadBalancer,
  LeastActiveLoadBalancer,
  TraceIdRequestInterceptor,
  UserInfoRequestInterceptor,
  RequestLogInterceptor,
  ResponseLogInterceptor,
  ResponseTransformInterceptor,
  ErrorHandlerInterceptor,
  type LoadBalanceStrategy,
  type LoadBalancer,
  type ServiceCallOptions,
  type ServiceCallResponse,
  type ServiceRequestInterceptor,
  type ServiceResponseInterceptor,
  type ServiceCallError,
} from './microservice';
// Governance 模块
export {
  CircuitBreaker,
  CircuitBreakerState,
  RateLimiter,
  RetryStrategyImpl,
  type CircuitBreakerOptions,
  type CircuitBreakerStats,
  type RateLimiterOptions,
  type RetryStrategy,
} from './microservice';
// Tracing 模块
export {
  Tracer,
  ConsoleTraceCollector,
  MemoryTraceCollector,
  SpanStatus,
  SpanKind,
  type TraceId,
  type SpanId,
  type SpanContext,
  type Span,
  type SpanTags,
  type SpanEvent,
  type TracingOptions,
  type TraceCollector,
} from './microservice';
// Monitoring 模块
export {
  ServiceMetricsCollector,
  type ServiceCallMetrics,
  type ServiceInstanceHealth,
  type MonitoringOptions,
} from './microservice';

